// =======================================================
// This file is auto generated by [DataConvertor for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  Sep 27, 2018 at 2:11:17 pm
// ======================================================


import Foundation


class QBInfo {
    var rank : String? = nil; // Rank
    var playerName : String? = nil; // PlayerName
    var playerNumber : String? = nil; // PlayerNumber
    var teamCode : String? = nil; // TeamCode
    var teamName : String? = nil; // TeamName
    var physical : String? = nil; // Physical
    var birthdateAndPlace : String? = nil; // BirthdateAndPlace
    var college : String? = nil; // College
    var experience : String? = nil; // Experience
    var highSchool : String? = nil; // HighSchool
}