// =======================================================
// This file is auto generated by [DataConvertor for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  Sep 27, 2018 at 2:11:17 pm
// ======================================================


import Foundation


private let AUTO_PLIST_QBINFO_PATH = Bundle.main.path(forResource: "QBInfo", ofType: "plist")

private let AUTO_PLIST_QBINFO_KEY_RANK = "rank"   // Rank
private let AUTO_PLIST_QBINFO_KEY_PLAYERNAME = "playerName"   // PlayerName
private let AUTO_PLIST_QBINFO_KEY_PLAYERNUMBER = "playerNumber"   // PlayerNumber
private let AUTO_PLIST_QBINFO_KEY_TEAMCODE = "teamCode"   // TeamCode
private let AUTO_PLIST_QBINFO_KEY_TEAMNAME = "teamName"   // TeamName
private let AUTO_PLIST_QBINFO_KEY_PHYSICAL = "physical"   // Physical
private let AUTO_PLIST_QBINFO_KEY_BIRTHDATEANDPLACE = "birthdateAndPlace"   // BirthdateAndPlace
private let AUTO_PLIST_QBINFO_KEY_COLLEGE = "college"   // College
private let AUTO_PLIST_QBINFO_KEY_EXPERIENCE = "experience"   // Experience
private let AUTO_PLIST_QBINFO_KEY_HIGHSCHOOL = "highSchool"   // HighSchool


class QBInfoManager {

    public static let sharedManager = QBInfoManager()
    private init(){}

    private var _qBInfos = [QBInfo]()

    func allQBInfos() -> [QBInfo]{

        if _qBInfos.count > 0 {
            return _qBInfos
        }

        if let allDatas = NSArray(contentsOfFile: AUTO_PLIST_QBINFO_PATH!) {

            for dict in allDatas {
                guard let dict = dict as? [String: AnyObject] else {continue}

                let qBInfo = QBInfo()
                qBInfo.rank = dict[AUTO_PLIST_QBINFO_KEY_RANK] as? String // Rank
                qBInfo.playerName = dict[AUTO_PLIST_QBINFO_KEY_PLAYERNAME] as? String // PlayerName
                qBInfo.playerNumber = dict[AUTO_PLIST_QBINFO_KEY_PLAYERNUMBER] as? String // PlayerNumber
                qBInfo.teamCode = dict[AUTO_PLIST_QBINFO_KEY_TEAMCODE] as? String // TeamCode
                qBInfo.teamName = dict[AUTO_PLIST_QBINFO_KEY_TEAMNAME] as? String // TeamName
                qBInfo.physical = dict[AUTO_PLIST_QBINFO_KEY_PHYSICAL] as? String // Physical
                qBInfo.birthdateAndPlace = dict[AUTO_PLIST_QBINFO_KEY_BIRTHDATEANDPLACE] as? String // BirthdateAndPlace
                qBInfo.college = dict[AUTO_PLIST_QBINFO_KEY_COLLEGE] as? String // College
                qBInfo.experience = dict[AUTO_PLIST_QBINFO_KEY_EXPERIENCE] as? String // Experience
                qBInfo.highSchool = dict[AUTO_PLIST_QBINFO_KEY_HIGHSCHOOL] as? String // HighSchool
                _qBInfos.append(qBInfo)
            }
        }
        return _qBInfos
    }
}