// =======================================================
// This file is auto generated by [DataConvertor for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  Sep 27, 2018 at 1:57:31 pm
// ======================================================


import Foundation


class QBPerf {
    var rank : Int? = nil; // Rank
    var playerName : String? = nil; // PlayerName
    var teamCode : String? = nil; // TeamCode
    var teamName : String? = nil; // TeamName
    var gamesPlayed : Int? = nil; // GamesPlayed
    var completions : Int? = nil; // Completions
    var attempts : Int? = nil; // Attempts
    var completionPercentage : Double? = nil; // CompletionPercentage
    var attemptsPerGame : Double? = nil; // AttemptsPerGame
    var yards : Int? = nil; // Yards
    var averagePerCompletion : Double? = nil; // AveragePerCompletion
    var yardsPerGame : Double? = nil; // YardsPerGame
    var touchdownPasses : Int? = nil; // TouchdownPasses
    var interceptions : Int? = nil; // Interceptions
    var firstDowns : Int? = nil; // FirstDowns
    var firstDownPercentage : Double? = nil; // FirstDownPercentage
    var longest : String? = nil; // Longest
    var sacks : Int? = nil; // Sacks
    var rating : Double? = nil; // Rating
}
